services:
  dmk_m_backend:
    platform: linux/amd64
    build: .
    ports:
      - "12380:8000"
    volumes:
      - ./dist:/app/backend/dist:ro
      - ./backend/.env:/app/backend/.env:ro
    restart: unless-stopped
    depends_on:
      - dmk_m_redis

  dmk_m_redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
