services:
  dmk_m_backend:
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=dmk_m_redis
      - DATABASE_HOST=host.docker.internal
    volumes:
      - ./dist:/app/backend/dist:ro
    restart: unless-stopped

  dmk_m_redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
